### PR TITLE
Updated README.md

### PR DESCRIPTION
**Pull request by Aholicknight**
The homebanner was outdated and needed an update. It said below "Registrations is now open" when its not.

### CODE REVIEW

**Comment by BrettMayson** [comment]
We are waiting for a new asset package for 2018 from the artists. Readme change will be pulled but the other two won't.

**Comment by Aholicknight** [comment]
Alright, I will close this pull request and make a new one with the `README.md` updated. @brettmayson What theme won for 2018? Was it the 90s theme?

**Review by BrettMayson — CHANGES_REQUESTED** [review]
Remove the changes to www/index.php and www/img/homebanner.png and then this will be merged.

**Comment by Aholicknight** [comment]
@brettmayson Do you know how I can? I have no idea how to do this.

**Comment by BrettMayson** [comment]
`git checkout e2b52f9 -- www/index.php www/img/homebanner.png`
That should do it

**Comment by Aholicknight** [comment]
@brettmayson That should fix it. I replaced the old one with the new one.

**Comment by Aholicknight** [comment]
@brettmayson Now if you dont mind asking do you know what theme won? I remember paul telling me that they will begin the picking mid feb 
image

**Comment by BrettMayson** [comment]
We ended up with "Future Focus" as the 2018 theme.

**Comment by Aholicknight** [comment]
@brettmayson Yeah I can see that theme winning instead of the 90s theme. It would be fun to teach the campers about old tech like Dial up Modems and how they work. I also have a 56K Dial up modem called SupraFAXModem 288. I hope a lot of campers or even mentors will get nostalgic over the modem. Me and Garry are planning to bring a ton of 90s related tech (if the theme got accepted) like floppy discs, Unreal Gold, and even a Voodoo 2.

**Pull request merged**
