### PR TITLE
iq sponsor

### PR DESCRIPTION
**Pull request by rye761**

### CODE REVIEW

**Comment by BrettMayson** [comment]
I will merge your commit at a later date, AJ's changes to the backend will break the site if the prod database isn't prepped beforehand.

**Comment by BrettMayson** [comment]
If you want this done earlier it'd be best to cherry pick it from master to another branch and push that to live

**Comment by rye761** [comment]
Do you think we could have it done within a week or so without cherry picking?

**Comment by BrettMayson** [comment]
My plan is to do it this week

**Comment by rye761** [comment]
Any updates on this?

**Pull request closed without merging**
